### ISSUE TITLE
Without Babel loader this plugin generated minified ES2015 code.

### ISSUE THREAD

**Issue by mohsen1** [boopathi/babili-webpack-plugin#17]
It might be expected behavior but it's not very obvious

**Comment by boopathi** [comment]
This plugin doesn't transform ES6 to ES5 anywhere. Babili does a few optimizations that result in a few `var`s instead of `let`s. Other than that there are no other ES6->ES5 transformations that I see.

**Comment by boopathi** [comment]
Oops. Sorry. Read it wrong ... Assumed - ES2015 as ES5.

**Comment by mohsen1** [comment]
I'm confused, in this webpack config it does transpile down to ES5 without any babel-loader: https://github.com/blacksonic/typescript-webpack-tree-shaking/blob/master/webpack.es2015.prod.config.js

**Comment by mohsen1** [comment]
Oh never mind I can see the `class` keyword in minified code.

**Comment by boopathi** [comment]
The aim of babili is to support minification for the latest JavaScript standard (from ES5). Transpiling it to your required target language - previous javascript version is upto you. This babili-plugin is just a wrapper over babili.
