### ISSUE TITLE
cannot transform into es5?

### ISSUE THREAD

**Issue by beiciye** [boopathi/babili-webpack-plugin#21]
Hi, thanks for your effort !

Is there a way to transform minified code into es5 code?

**Comment by boopathi** [comment]
It's better to convert the code to ES5 and then minify it.

**Comment by beiciye** [comment]
That's to say,  tree shaking is still not working.

**Comment by thasmo** [comment]
@boopathi How would we use tree-shaking and transpilation to ES5?
