### ISSUE TITLE
question: diagnosing production build problems with babili

### ISSUE THREAD

**Issue by rosskevin** [boopathi/babili-webpack-plugin#25]
I'm not quite sure here where to start, so any guidance would be helpful.  When I build and add the `babili-webpack-plugin`, I receive the following when I use it in the browser:

```
Uncaught ReferenceError: X is not defined
    at Object.<anonymous> (6bc3975….vendor.js:38)
    at Y (6bc3975….vendor.js:38)
    at Object.W.exports (6bc3975….vendor.js:38)
    at Y (6bc3975….vendor.js:38)
    at Object.W.exports.ae (6bc3975….vendor.js:38)
    at Y (6bc3975….vendor.js:38)
    at Object.X.J.oe (6bc3975….vendor.js:38)
    at Y (6bc3975….vendor.js:38)
    at Object.W.exports (6bc3975….vendor.js:38)
    at Y (6bc3975….vendor.js:38)
```

## Details

- works in `development` mode (devtool enabled)
- doesn't work when in production
- I dump the webpack configs as a string but minimize the plugin output (for debugging purposes), [here is a gist of the two files](https://gist.github.com/rosskevin/0ba540bb9287a21912db2d18136b612c), the only notable diff to production is: 
    1. devtool: false
    2. removal HMR plugins
    3. addition of babili

What can I do to make progress on this - I feel pretty stuck.

**Comment by rosskevin** [comment]
ugh, I just added .babelrc to the gist and see a diff there.  Will remove and try now.

**Comment by boopathi** [comment]
Looks like a babili error and not babili-webpack-plugin error. You could as well generate a minimal repro case and report it in babili repo.

**Comment by rosskevin** [comment]
Thanks @boopathi - I just altered the babelrc and same thing.

The problem is that how do I boil down a huge app to a repro case when I really can't read the code. ?

**Comment by boopathi** [comment]
I agree it is hard to detect these bugs.

You can pretty print the syntax and look around the code where it is throwing the error. And try that part of the code in isolation without the rest of the code. Maybe, it helps for this error.
