### ISSUE TITLE
Configurable transformer, plugins and presets.

### ISSUE THREAD

**Issue by gcphost** [boopathi/babili-webpack-plugin#3]
Hi

Thanks for the plugin.

I am using Angular 2 Final and can't use all of the plugins listed in `babel-preset-babili` so it would be nice to have the option to disable presets and provide an array of plugins.
- Will

**Comment by gcphost** [comment]
Pr #4

**Comment by boopathi** [comment]
This will be done on babili's side as Minifier Options - babel/babili#162

Adding custom plugins apart from babili provided options doesn't sound right IMO. Also, if the user wants selective optimizations / disable one plugin from the preset, then with this approach, s/he has to pass in all other plugins that babili uses - this is just bad.

**Comment by boopathi** [comment]
babel/babili#162 is merged.
